import Head from "next/head";
import { Button } from "design-system";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleClick = () => {
    console.log("t");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        t
        <Button onClick={handleClick}>
          Next page
        </Button>
      </div>
    </div>
  );
}
